name: shop_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #http client
  dio: ^4.0.4

  #copyWith
  copy_with_extension: ^4.0.0

  #dependency injection
  get_it: ^7.2.0
  
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.1
  provider: ^6.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  email_validator: ^2.0.1

  #auth
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5

  #fonts
  font_awesome_flutter: ^9.2.0

  #routing
  auto_route: ^3.2.1 

  #image picker
  image_picker: ^0.8.4+4

  #bloc
  flutter_bloc: ^8.0.1

  #form validators
  formz: ^0.4.1

  #code generation
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  auto_route_generator: ^3.2.1
  copy_with_extension_gen: ^4.0.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Lato
      fonts: 
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
